### ISSUE TITLE
Settings not displayed

### ISSUE THREAD

**Issue by paultvis** [opengento/magento2-product-breadcrumbs#2]
Hi,

I have installed your module and on categories it works great. On products, while the page loads the breadcrumb shows the full path, but then changes to show Home / Product. On the description it talks about settings, but where are then updated. There does not seem to be any menu options in the admin panel.

Thanks

**Comment by thomas-kl1** [comment]
Hello @paultvis 

That's right the path of the configuration is missing in the readme!

You can find the configuration in Stores > Configuration > Catalog > Catalog > Search Engine Optimization

**Comment by paultvis** [comment]
Thanks for that. So, I checked the settings and all are enabled. However, when navigating from a category page which has the correct breadcrumb to a product page, the breadcrumb starts correct with the full path, but then gets changed to home / Product. Should there be any default breadcrumb generation that is disabled?

**Comment by thomas-kl1** [comment]
@paultvis I've noticed a small bug with luma, for the server sided breadcrumb, the first node "home" was missing on the product pages.

Could you tell me what are you trying to achieve? This module allows you to render the breadcrumbs from server side instead of client side (as it is in Magento vanilla). This module comes with an option in order to allow to keep the client sided breadcrumbs (based on customer navigation) to override the one printed by servide side.

**Comment by paultvis** [comment]
@thomas-kl1 we are looking to get the full path (based on the category) for a product rather than the navigated route. I have just updated the setting for override on client side and now doing what we are looking for. 

That default config is a little counter intuitive. The module is added to change the behaviour of the breadcrumb, but then the default settings undo the changes that you have just added to the module for. Just a comment.

**Comment by thomas-kl1** [comment]
@paultvis it depends of needs. That's why there's the option to allow the client side génération to override the server sided one.
Actually most of use cases are to allow the robots to see a default breadcrumbs, while the customer continue to see the breadcrumbs based on their navigation.

As you do, I've also a few projects where merchant needs a single breadcrumbs by products. This module allows to fullfil both needs. 😄 

I'm closing this issues but feel free to open a new issue if you see any other issue or you'd like improvements/features.

If you think this module helped you (and because it's free 🤭) you can add a star ⭐ !

**Comment by paultvis** [comment]
Thanks for your help @thomas-kl1 . Understand the logic now. Great module!
